<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQXliWFm\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQXliWFm/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQXliWFm.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQXliWFm\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQXliWFm\App_KernelDevDebugContainer([
    'container.build_hash' => 'QXliWFm',
    'container.build_id' => '9a51d10b',
    'container.build_time' => 1587562397,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQXliWFm');
