<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container89OSUza\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container89OSUza/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container89OSUza.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container89OSUza\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container89OSUza\App_KernelDevDebugContainer([
    'container.build_hash' => '89OSUza',
    'container.build_id' => '3a0a7865',
    'container.build_time' => 1587481218,
], __DIR__.\DIRECTORY_SEPARATOR.'Container89OSUza');
