<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAYLU4NK\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAYLU4NK/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAYLU4NK.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAYLU4NK\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerAYLU4NK\App_KernelDevDebugContainer([
    'container.build_hash' => 'AYLU4NK',
    'container.build_id' => '78962bf0',
    'container.build_time' => 1587548154,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAYLU4NK');
